-- MySQL Script generated by MySQL Workbench
-- Mon 25 Sep 2017 04:49:05 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airbnb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airbnb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb2` DEFAULT CHARACTER SET utf8 ;
USE `airbnb2` ;

-- -----------------------------------------------------
-- Table `airbnb2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb2`.`users` (
  `userID` BIGINT(20) NOT NULL,
  `host` TINYINT(1) NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `image_URL` VARCHAR(200) NULL,
  `verified_from_admin` TINYINT(1) NULL,
  `username` VARCHAR(45),
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb2`.`houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb2`.`houses` (
  `houseID` BIGINT(20) NOT NULL,
  `houseURL` VARCHAR(80) NULL,
  `scrapeID` VARCHAR(45) NULL,
  `last_scraped` DATE NULL,
  `name` VARCHAR(50) NULL,
  `summary` VARCHAR(1000) NULL,
  `space` VARCHAR(1000) NULL,
  `description` VARCHAR(1000) NULL,
  `experiences_offered` VARCHAR(200) NULL,
  `neighborhood_overview` VARCHAR(500) NULL,
  `notes` VARCHAR(300) NULL,
  `transit` VARCHAR(500) NULL,
  `thumbnailURL` VARCHAR(200) NULL,
  `mediumURL` VARCHAR(200) NULL,
  `pictureURL` VARCHAR(200) NULL,
  `xl_pictureURL` VARCHAR(200) NULL,
  `hostID` BIGINT(20) NOT NULL,
  `hostURL` VARCHAR(200) NULL,
  `host_name` VARCHAR(30) NULL,
  `host_since` DATE NULL,
  `host_location` VARCHAR(100) NULL,
  `host_about` VARCHAR(300) NULL,
  `host_response_time` VARCHAR(100) NULL,
  `host_response_rate` VARCHAR(45) NULL,
  `host_is_superhost` VARCHAR(5) NULL,
  `host_thumbnail_url` VARCHAR(200) NULL,
  `host_picture_url` VARCHAR(200) NULL,
  `host_neighbourhood` VARCHAR(45) NULL,
  `host_listings_count` INT NULL,
  `host_total_listings_count` INT NULL,
  `host_verifications` VARCHAR(150) NULL,
  `host_has_profile_pic` VARCHAR(5) NULL,
  `host_identity_verified` VARCHAR(5) NULL,
  `street` VARCHAR(45) NULL,
  `neighbourhood` VARCHAR(100) NULL,
  `neighbourhood_cleansed` VARCHAR(45) NULL,
  `neighbourhood_group_cleansed` VARCHAR(100) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipcode` INT NULL,
  `market` VARCHAR(45) NULL,
  `country_code` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `is_location_exact` VARCHAR(5) NULL,
  `property_type` VARCHAR(45) NULL,
  `room_type` VARCHAR(45) NULL,
  `accommodates` INT NULL,
  `bathrooms` FLOAT NULL,
  `bedrooms` INT NULL,
  `beds` INT NULL,
  `bed_type` VARCHAR(45) NULL,
  `amenities` VARCHAR(300) NULL,
  `square_feet` INT NULL,
  `price` INT NULL,
  `weekly_price` VARCHAR(45) NULL,
  `monthly_price` VARCHAR(45) NULL,
  `security_deposit` VARCHAR(45) NULL,
  `cleaning_fee` INT NULL,
  `guests_included` INT NULL,
  `extra_people` VARCHAR(45) NULL,
  `minimum_nights` INT NULL,
  `maximum_nights` INT NULL,
  `calendar_updated` VARCHAR(45) NULL,
  `has_availability` VARCHAR(5) NULL,
  `availability_30` INT NULL,
  `availability_60` INT NULL,
  `availability_90` INT NULL,
  `availability_365` INT NULL,
  `calendar_last_scraped` VARCHAR(45) NULL,
  `number_of_reviews` INT NULL,
  `first_review` VARCHAR(45) NULL,
  `last_review` VARCHAR(45) NULL,
  `review_scores_rating` INT NULL,
  `review_scores_accuracy` INT NULL,
  `review_scores_cleanliness` INT NULL,
  `review_scores_checkin` INT NULL,
  `review_scores_communication` INT NULL,
  `review_scores_location` INT NULL,
  `review_scores_value` INT NULL,
  `requires_license` VARCHAR(5) NULL,
  `license` VARCHAR(45) NULL,
  `jurisdiction_names` VARCHAR(45) NULL,
  `instant_bookable` VARCHAR(45) NULL,
  `cancellation_policy` VARCHAR(45) NULL,
  `require_guest_profile_picture` VARCHAR(5) NULL,
  `require_guest_phone_verification` VARCHAR(45) NULL,
  `calculated_host_listings_count` INT NULL,
  `reviews_per_month` FLOAT NULL,
  `ac` TINYINT(1) NULL,
  `elevator` TINYINT(1) NULL,
  `heating` TINYINT(1) NULL,
  `kitchen` TINYINT(1) NULL,
  `parking` TINYINT(1) NULL,
  `tv` TINYINT(1) NULL,
  `wifi` TINYINT(1) NULL,
  PRIMARY KEY (`houseID`),
  INDEX `fk_houses_users1_idx` (`hostID` ASC),
  CONSTRAINT `fk_houses_users1`
    FOREIGN KEY (`hostID`)
    REFERENCES `airbnb2`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb2`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb2`.`reviews` (
  `reviewID` BIGINT(20) NOT NULL,
  `houseID` BIGINT(20) NOT NULL,
  `reviewerID` BIGINT(20) NOT NULL,
  `date` DATE NULL,
  `stars` VARCHAR(30) NULL,
  `comments` VARCHAR(500) NULL,
  PRIMARY KEY (`reviewID`),
  INDEX `fk_reviews_houses1_idx` (`houseID` ASC),
  INDEX `fk_reviews_users1_idx` (`reviewerID` ASC),
  CONSTRAINT `fk_reviews_houses1`
    FOREIGN KEY (`houseID`)
    REFERENCES `airbnb2`.`houses` (`houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`reviewerID`)
    REFERENCES `airbnb2`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb2`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb2`.`calendar` (
  `houseID` BIGINT(20) NOT NULL,
  `date` DATE NOT NULL,
  `available` CHAR NULL,
  `price` FLOAT NULL,
  `id` BIGINT(20) NOT NULL,
  `guestID` BIGINT(20),
  INDEX `fk_calendar_houses1_idx` (`houseID` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_calendar_houses1`
    FOREIGN KEY (`houseID`)
    REFERENCES `airbnb2`.`houses` (`houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb2`.`user_has_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airbnb2`.`user_has_messages` (
  `senderID` BIGINT(20) NOT NULL,
  `receiverID` BIGINT(20) NOT NULL,
  `message` VARCHAR(500) NULL,
  `messageID` BIGINT(20) NOT NULL,
  CONSTRAINT `senderID`
    FOREIGN KEY (`senderID`)
    REFERENCES `airbnb2`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiverID`
    FOREIGN KEY (`receiverID`)
    REFERENCES `airbnb2`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
